#!/bin/bash
#
#/path/to/initapp /path/to/target_dir /path/to/app_dir

# https://github.com/SunriseDigital/sdx/blob/master/initapp

### 引数チェック
#target_dir
if [ -n "$1" ]
then
	target_dir=$1

	first_chr=`echo ${target_dir} | cut -c 1`
	if [ "$first_chr" != / ]
	then
		echo Use full path start from "/" for target_dir
		exit
	fi

	target_name=`echo ${target_dir} | sed -e "s/.*\/\([^/]*\)\$/\1/g"`

else
	echo Please enter /path/to/target_dir.
	exit
fi

#app_dir
if [ -n "$2" ]
then
	app_dir=$2

	first_chr=`echo ${app_dir} | cut -c 1`
	if [ "$first_chr" != / ]
	then
		echo Use full path start from "/" for app_dir
		exit
	fi

	app_name=`echo ${app_dir} | sed -e "s/.*\/\([^/]*\)\$/\1/g"`

else
	echo Please enter /path/to/app_dir.
	exit
fi


### ディレクトリ作成
mkdirs=(\
	${target_dir}/css \
	${target_dir}/css/i18n \
	${target_dir}/img \
	${target_dir}/img/i18n \
	${target_dir}/js \
	${target_dir}/js/i18n \
	${app_dir}/app \
	${app_dir}/app/views \
	${app_dir}/app/views/default \
	${app_dir}/app/views/default/error \
	${app_dir}/app/views/default/index \
	${app_dir}/app/views/default/magazine \
	${app_dir}/app/views/i18n \
	${app_dir}/app/views/mobile \
	${app_dir}/app/views/mobile/error \
	${app_dir}/app/views/mobile/index \
	${app_dir}/app/views/mobile/magazine \
	${app_dir}/cache \
	${app_dir}/config \
	${app_dir}/config/i18n \
	${app_dir}/config/magazine \
	${app_dir}/i18n \
	${app_dir}/log \
	${app_dir}/logs \
	${app_dir}/tmp \
	${app_dir}/templates_c
)

### 作成実行
#mkdirFromArray


### 書き込みディレクトリのパーミッション変更
chmod 0777 ${app_dir}/cache
chmod 0777 ${app_dir}/log
chmod 0777 ${app_dir}/logs
chmod 0777 ${app_dir}/tmp
chmod 0777 ${app_dir}/tmp/templates_c

# 対象：app_dir

# TODO: app/ 作成

# TODO: app/controllers -> /home/source/sites/magazine/application/controllers シンボリックリンク作成

# TODO: app/views にviewsディレクトリをコピー
# TODO: app/views/global -> /home/source/sites/magazine/common/views シンボリックリンク作成
# TODO: app/views/sdx -> /home/source/sites/sdx/views シンボリックリンク作成

# TODO: cache/ 作成

# TODO: config にconfigディレクトリをコピー
# TODO: config/global -> /home/source/sites/magazine/common/config シンボリックリンク作成
# TODO: config/sdx -> /home/source/sites/sdx/config シンボリックリンク作成
# TODO: config/i18n/ 作成

# TODO: i18n/ 作成

# TODO: log/ 作成

# TODO: logs/ 作成

# TODO: tmp/ 作成

# TODO: sunrise コピー


# 対象：target_dir

# TODO: webディレクトリをコピー

# TODO: css/ 作成
# TODO: css/i18n 作成
# TODO: css/global -> /home/source/sites/magazine/common/css シンボリックリンク作成

# TODO: js/ 作成
# TODO: js/i18n 作成
# TODO: js/global -> /home/source/sites/magazine/common/js シンボリックリンク作成
# TODO: js/sdx -> /home/source/sites/sdx/js シンボリックリンク作成
