#!/bin/bash
#
#/path/to/initapp /path/to/target_dir /path/to/app_dir

# https://github.com/SunriseDigital/sdx/blob/master/initapp

### ディレクトリ名を取得
script_dir=`dirname $0`

#共通関数をinclude
sdx_dir="/home/source/sites/sdx"
. ${sdx_dir}/bin/func

### 引数チェック
#target_dir
if [ -n "$1" ]
then
	target_dir=$1

	first_chr=`echo ${target_dir} | cut -c 1`
	if [ "$first_chr" != / ]
	then
		echo Use full path start from "/" for target_dir
		exit
	fi

	target_name=`echo ${target_dir} | sed -e "s/.*\/\([^/]*\)\$/\1/g"`

else
	echo Please enter /path/to/target_dir.
	exit
fi

#app_dir
if [ -n "$2" ]
then
	app_dir=$2

	first_chr=`echo ${app_dir} | cut -c 1`
	if [ "$first_chr" != / ]
	then
		echo Use full path start from "/" for app_dir
		exit
	fi

	app_name=`echo ${app_dir} | sed -e "s/.*\/\([^/]*\)\$/\1/g"`

else
	echo Please enter /path/to/app_dir.
	exit
fi

### ディレクトリ作成
mkdirs=(\
	${target_dir}/css \
	${target_dir}/css/i18n \
	${target_dir}/img \
	${target_dir}/img/i18n \
	${target_dir}/js \
	${target_dir}/js/i18n \
	${app_dir}/app \
	${app_dir}/app/views \
	${app_dir}/app/views/default \
	${app_dir}/app/views/default/error \
	${app_dir}/app/views/default/index \
	${app_dir}/app/views/default/magazine \
	${app_dir}/app/views/i18n \
	${app_dir}/app/views/mobile \
	${app_dir}/app/views/mobile/error \
	${app_dir}/app/views/mobile/index \
	${app_dir}/app/views/mobile/magazine \
	${app_dir}/cache \
	${app_dir}/config \
	${app_dir}/config/i18n \
	${app_dir}/config/magazine \
	${app_dir}/i18n \
	${app_dir}/log \
	${app_dir}/logs \
	${app_dir}/tmp \
	${app_dir}/templates_c
)

### 作成実行
mkdirFromArray

### 書き込みディレクトリのパーミッション変更
chmod 0777 ${app_dir}/cache
chmod 0777 ${app_dir}/log
chmod 0777 ${app_dir}/logs
chmod 0777 ${app_dir}/tmp
chmod 0777 ${app_dir}/tmp/templates_c

### ファイルをコピー
cp_from(\
	${script_dir}/copy/config/magazine/category.yml \
	${script_dir}/copy/config/magazine/group.yml \
	${script_dir}/copy/config/magazine/list.yml \
	${script_dir}/copy/config/mobile_route.yml \
	${script_dir}/copy/config/route.yml \
	${script_dir}/copy/config/sys.yml \
	${script_dir}/copy/viwes/default/error/404.tpl \
	${script_dir}/copy/viwes/default/error/500.tpl \
	${script_dir}/copy/viwes/default/index/index.tpl \
	${script_dir}/copy/viwes/default/magazine/article/1/body.tpl \
	${script_dir}/copy/viwes/default/magazine/article/1/outline.tpl \
	${script_dir}/copy/viwes/default/magazine/article.tpl \
	${script_dir}/copy/viwes/default/magazine/base.tpl \
	${script_dir}/copy/viwes/default/magazine/category.tpl \
	${script_dir}/copy/viwes/default/magazine/group.tpl \
	${script_dir}/copy/viwes/default/magazine/index.tpl \
	${script_dir}/copy/viwes/mobile/error/404.tpl \
	${script_dir}/copy/viwes/mobile/error/500.tpl \
	${script_dir}/copy/viwes/mobile/index/index.tpl \
	${script_dir}/copy/viwes/mobile/magazine/article.tpl \
	${script_dir}/copy/viwes/mobile/magazine/base.tpl \
	${script_dir}/copy/viwes/mobile/magazine/category.tpl \
	${script_dir}/copy/viwes/mobile/magazine/group.tpl \
	${script_dir}/copy/viwes/mobile/magazine/index.tpl \
	${script_dir}/copy/gitignore
)

cp_to(\
	${app_dir}/config/magazine/category.yml \
	${app_dir}/config/magazine/group.yml \
	${app_dir}/config/magazine/list.yml \
	${app_dir}/config/mobile_route.yml \
	${app_dir}/config/route.yml \
	${app_dir}/config/sys.yml \
	${app_dir}/app/viwes/default/error/404.tpl \
	${app_dir}/app/viwes/default/error/500.tpl \
	${app_dir}/app/viwes/default/index/index.tpl \
	${app_dir}/app/viwes/default/magazine/article/1/body.tpl \
	${app_dir}/app/viwes/default/magazine/article/1/outline.tpl \
	${app_dir}/app/viwes/default/magazine/article.tpl \
	${app_dir}/app/viwes/default/magazine/base.tpl \
	${app_dir}/app/viwes/default/magazine/category.tpl \
	${app_dir}/app/viwes/default/magazine/group.tpl \
	${app_dir}/app/viwes/default/magazine/index.tpl \
	${app_dir}/app/viwes/mobile/error/404.tpl \
	${app_dir}/app/viwes/mobile/error/500.tpl \
	${app_dir}/app/viwes/mobile/index/index.tpl \
	${app_dir}/app/viwes/mobile/magazine/article.tpl \
	${app_dir}/app/viwes/mobile/magazine/base.tpl \
	${app_dir}/app/viwes/mobile/magazine/category.tpl \
	${app_dir}/app/viwes/mobile/magazine/group.tpl \
	${app_dir}/app/viwes/mobile/magazine/index.tpl \
	${app_dir}/.gitignore
)

### コピー実行
copyFromArray

### シンボリックリンク作成
ln_from=(\
	${script_dir}/application/controllers \
	${script_dir}/common/views \
	${sdx_dir}/views \
	${script_dir}/common/config \
	${sdx_dir}/config \
	${script_dir}/common/css \
	${sdx_dir}/css \
	${script_dir}/common/js \
	${sdx_dir}/js
)

ln_to(\
	${app_dir}/app/controllers \
	${app_dir}/app/views/global \
	${app_dir}/app/views/sdx \
	${app_dir}/config/global \
	${app_dir}/config/sdx \
	${target_dir}/css/global \
	${target_dir}/css/sdx \
	${target_dir}/js/global \
	${target_dir}/js/sdx
)

### リンク作成
if [ "$force_symlink" = "TRUE" ]
then
	symlinkFromArrayForce
else
	symlinkFromArray
fi

### テキスト内に置換の必要なファイル群
replaceAndCopy ${sdx_dir}/copy/sunrise ${app_dir}/sunrise

if [ ! -x ${app_dir}/sunrise ]
then
	chmod 0777 ${app_dir}/sunrise
fi

replaceAndCopy ${script_dir}/copy/web/index.php ${target_dir}/index.php
replaceAndCopy ${script_dir}/copy/web/mobile_index.php ${target_dir}/mobile_index.php

replaceAndCopy ${script_dir}/copy/config/Configuration.php ${app_dir}/config/Configuration.php


# 対象：app_dir

# TODO: app/ 作成

# TODO: app/controllers -> /home/source/sites/magazine/application/controllers シンボリックリンク作成

# TODO: app/views にviewsディレクトリをコピー
# TODO: app/views/global -> /home/source/sites/magazine/common/views シンボリックリンク作成
# TODO: app/views/sdx -> /home/source/sites/sdx/views シンボリックリンク作成

# TODO: cache/ 作成

# TODO: config にconfigディレクトリをコピー
# TODO: config/global -> /home/source/sites/magazine/common/config シンボリックリンク作成
# TODO: config/sdx -> /home/source/sites/sdx/config シンボリックリンク作成
# TODO: config/i18n/ 作成

# TODO: i18n/ 作成

# TODO: log/ 作成

# TODO: logs/ 作成

# TODO: tmp/ 作成

# TODO: sunrise コピー


# 対象：target_dir

# TODO: webディレクトリをコピー

# TODO: css/ 作成
# TODO: css/i18n 作成
# TODO: css/global -> /home/source/sites/magazine/common/css シンボリックリンク作成

# TODO: js/ 作成
# TODO: js/i18n 作成
# TODO: js/global -> /home/source/sites/magazine/common/js シンボリックリンク作成
# TODO: js/sdx -> /home/source/sites/sdx/js シンボリックリンク作成
